- name: demo on variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks:
    - name: print URL variable
      ansible.builtin.debug:
        msg: "{{ URL }}"





- name: demo on task variables
  hosts: localhost
  tasks:
    - name: print URL1 variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      vars:
        URL1: sample.com
    - name: print URL2 variable
      ansible.builtin.debug:
        msg: "{{ URL2 }}"
      vars:
        URL2: sample.com

    - name: print URL3 variable
      ansible.builtin.debug:
        msg: "{{ URL3 }}"
      vars:
        URL3: sample.com
    - name: print URL4 variable
      ansible.builtin.debug:
        msg: "{{ URL4 }}"
      vars:
        URL4: sample.com
    - name: print URL5 variable
      ansible.builtin.debug:
        msg: "{{ URL5 }}"
      vars:
        URL5: sample.com
    - name: print URL6 variable
      ansible.builtin.debug:
        msg: "{{ URL6 }}"
      vars:
        URL6: sample.com
    - name: print URL7 variable varma
      ansible.builtin.debug:
        msg: "{{ URL7 }}"
      vars:
        URL7: sample.com
    - name: print URL8 variable
      ansible.builtin.debug:
        msg: "{[ URL8 }}"
      vars:
        URL8: sample.com
    - name: print url9 variable
      ansible.builtin.debug:
        msg: "{{ URL9 }}"
      vars:
        URL9: sample.com
    - name: print URL10 variable
      ansible.builtin.debug:
        msg: "{{ URL10 }}"
      vars:
        URL10: sample.com

- name: register varable example
  hosts: localhost
  tasks:
    - name: get uptime of the server
      ansible.builtin.shell: uptime
      register: out
    - name: print out variable
      ansible.builtin.debug:
        msg: "{{ out }}"


