- name: demo on variables
  hosts: localhost
  vars:
    URL: sample.com
  tasks:
    - name: print URL variable
      ansible.builtin.debug:
        msg: "{{ URL }}"





- name: demo on task variables
  hosts: localhost
  tasks:
    - name: print URL1 variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
      vars:
        URL1: sample.com
    - name: print URL2 variable
      ansible.builtin.debug:
        msg: "{{ URL2 }}"
      vars:
        URL2: sample.com

    - name: print URL3 variable
      ansibile.builtin.debug:
        msg: "{{ URL3 }}"
      vars:
        URL3: sample.com
    - name: print URL4 variable
      ansible.builtin.debug:
        msg: "{{ URL4 }}"
      vars:
        URL4: sample.com
